{{- if .Values.potProvider.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zimmporter.fullname" . }}-bgutil-provider
  labels:
    {{- include "zimmporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: bgutil-provider
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.potProvider.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zimmporter.bgutilSelectorLabels" . | nindent 4 }}
{{- end }}
