apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zimmporter.fullname" . }}-api-config
  labels:
    {{- include "zimmporter.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "zimmporter.dbHost" . | quote }}
  DB_PORT: {{ include "zimmporter.dbPort" . | quote }}
  CELERY_BROKER: {{ include "zimmporter.celeryBroker" . | quote }}
  CELERY_BACKEND: {{ include "zimmporter.celeryBackend" . | quote }}
  MINIO_ENDPOINT: {{ .Values.minio.endpoint | quote }}
  MINIO_USE_SSL: {{ .Values.minio.useSSL | toString | quote }}
  REQUIRE_AUTH: {{ .Values.api.env.REQUIRE_AUTH | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.api.env.CORS_ALLOWED_ORIGINS | quote }}
{{- if .Values.caCert.enabled }}
  CA_CERT: {{ .Values.caCert.path | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zimmporter.fullname" . }}-worker-config
  labels:
    {{- include "zimmporter.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "zimmporter.dbHost" . | quote }}
  DB_PORT: {{ include "zimmporter.dbPort" . | quote }}
  CELERY_BROKER: {{ include "zimmporter.celeryBroker" . | quote }}
  CELERY_BACKEND: {{ include "zimmporter.celeryBackend" . | quote }}
  MINIO_ENDPOINT: {{ .Values.minio.endpoint | quote }}
  MINIO_USE_SSL: {{ .Values.minio.useSSL | toString | quote }}
{{- if .Values.caCert.enabled }}
  CA_CERT: {{ .Values.caCert.path | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zimmporter.fullname" . }}-frontend-config
  labels:
    {{- include "zimmporter.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_API_URL: {{ .Values.frontend.env.NEXT_PUBLIC_API_URL | quote }}
