{{- if .Values.cookies.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zimmporter.cookiesVolumeName" . }}
  labels:
    {{- include "zimmporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: cookies
spec:
  accessModes:
    {{- toYaml .Values.cookies.persistence.accessModes | nindent 4 }}
  {{- if .Values.cookies.persistence.storageClass }}
  storageClassName: {{ .Values.cookies.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.cookies.persistence.size }}
{{- end }}
