{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zimmporter.fullname" . }}-database
  labels:
    {{- include "zimmporter.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ .Values.database.rootPassword | default (randAlphaNum 20) | b64enc | quote }}
  user: {{ .Values.database.user | b64enc | quote }}
  password: {{ .Values.database.password | default (randAlphaNum 20) | b64enc | quote }}
  name: {{ .Values.database.name | b64enc | quote }}
{{- end }}
{{- if not .Values.s3.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zimmporter.fullname" . }}-s3
  labels:
    {{- include "zimmporter.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.s3.accessKey | b64enc | quote }}
  secret-key: {{ .Values.s3.secretKey | b64enc | quote }}
{{- end }}
---
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zimmporter.fullname" . }}-api-and-front-auth
  labels:
    {{- include "zimmporter.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.auth.apiKey | b64enc | quote }}
  oidc-client-secret: {{ .Values.auth.oidcClientSecret | b64enc | quote }}
  github-client-secret: {{ .Values.auth.githubClientSecret | b64enc | quote }}
  auth-secret: {{ .Values.auth.authSecret | b64enc | quote }}
{{- end }}
